import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

import Banner from '@/components/banner'
import Forecast from '@/components/forecast'

import Link from 'next/link'

import styles from '@/styles/Home.module.css'
import Layout from '@/components/layout'


const inter = Inter({ subsets: ['latin'] })

const Home = () => {
  return (
    <Layout>
      <Head>
        <title>Forecaster - Make and Review Forecasts</title>
        <meta name="description" content="Generated by me.  Not you." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner></Banner>

      <Link href='forecasts/create'>Create Forecast</Link><br />

      <Link href='forecasts/list'>List Forecasts</Link>
    </Layout>
  )
}

export default Home;