import Head from 'next/head'
import { Inter } from '@next/font/google'

import Banner from '@/components/banner'

import Link from 'next/link'

import styles from '@/styles/Home.module.css'
import Layout from '@/components/layout'


const inter = Inter({ subsets: ['latin'] })

const Home = () => {
  let author: string = '100'

  return (
    <Layout>
      <Head>
        <title>Forecaster - Make and Review Forecasts</title>
        <meta name="description" content="Generated by me.  Not you." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner></Banner>

      <Link href='forecast/create'>Create a Forecast</Link><br />

      {/* todo - pass in author here */}
      <Link href='forecasts/list'>List all Forecasts for author {author}</Link>
    </Layout>
  )
}

export default Home;